### ISSUE TITLE
Can u put vercel button for install

### ISSUE THREAD

**Issue by johnfelipe** [ahmadnurfadilah/zapfeed#1]
Is possible you put a vercel button
And documentation for install own instance in my vercel

**Comment by johnfelipe** [comment]
[14:05:32.127] Running build in Washington, D.C., USA (East) – iad1
    [14:05:32.479] Cloning github.com/johnfelipe/zapfeed (Branch: main, Commit: 8aa50f0)
    [14:05:32.969] Previous build cache not available
    [14:05:32.994] Cloning completed: 508.071ms
    [14:05:33.693] Running "vercel build"
    [14:05:34.673] Vercel CLI 37.1.2
    [14:05:38.243] Installing dependencies...
    [14:05:45.387] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
    [14:05:46.206] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
    [14:05:48.273] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
    [14:05:48.337] npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
    [14:05:48.539] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
    [14:06:03.821] 
    [14:06:03.821] > zapfeed@0.1.0 postinstall
    [14:06:03.821] > prisma generate
    [14:06:03.821] 
    [14:06:04.417] Prisma schema loaded from prisma/schema.prisma
    [14:06:05.340] 
    [14:06:05.341] ✔ Generated Prisma Client (v5.18.0) to ./node_modules/@prisma/client in 333ms
    [14:06:05.341] 
    [14:06:05.341] Start by importing your Prisma Client (See: http://pris.ly/d/importing-client)
    [14:06:05.341] 
    [14:06:05.341] Tip: Want real-time updates to your database without manual polling? Discover how with Pulse: https://pris.ly/tip-0-pulse
    [14:06:05.342] 
    [14:06:05.535] 
    [14:06:05.536] added 619 packages in 27s
    [14:06:05.536] 
    [14:06:05.536] 156 packages are looking for funding
    [14:06:05.537]   run `npm fund` for details
    [14:06:05.566] Detected Next.js version: 14.2.5
    [14:06:05.590] Running "npm run build"
    [14:06:05.764] 
    [14:06:05.765] > zapfeed@0.1.0 build
    [14:06:05.765] > next build
    [14:06:05.765] 
    [14:06:06.526] Attention: Next.js now collects completely anonymous telemetry regarding usage.
    [14:06:06.527] This information is used to shape Next.js' roadmap and prioritize features.
    [14:06:06.530] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
    [14:06:06.530] https://nextjs.org/telemetry
    [14:06:06.530] 
    [14:06:06.592]   ▲ Next.js 14.2.5
    [14:06:06.592] 
    [14:06:06.665]    Creating an optimized production build ...
    [14:06:29.652]  ⚠ Compiled with warnings
    [14:06:29.653] 
    [14:06:29.654] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.654] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
    [14:06:29.654] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    [14:06:29.655] 
    [14:06:29.655] Import trace for requested module:
    [14:06:29.655] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.656] ./node_modules/@prisma/driver-adapter-utils/dist/index.mjs
    [14:06:29.656] ./node_modules/@tidbcloud/prisma-adapter/dist/index.mjs
    [14:06:29.657] ./auth.ts
    [14:06:29.657] 
    [14:06:29.657] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.657] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
    [14:06:29.657] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    [14:06:29.658] 
    [14:06:29.658] Import trace for requested module:
    [14:06:29.658] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.658] ./node_modules/@prisma/driver-adapter-utils/dist/index.mjs
    [14:06:29.658] ./node_modules/@tidbcloud/prisma-adapter/dist/index.mjs
    [14:06:29.658] ./auth.ts
    [14:06:29.659] 
    [14:06:29.659] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.659] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
    [14:06:29.659] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    [14:06:29.659] 
    [14:06:29.659] Import trace for requested module:
    [14:06:29.660] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.660] ./node_modules/@prisma/driver-adapter-utils/dist/index.mjs
    [14:06:29.660] ./node_modules/@tidbcloud/prisma-adapter/dist/index.mjs
    [14:06:29.660] ./auth.ts
    [14:06:29.660] 
    [14:06:29.660] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.660] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
    [14:06:29.661] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    [14:06:29.661] 
    [14:06:29.661] Import trace for requested module:
    [14:06:29.661] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.661] ./node_modules/@prisma/driver-adapter-utils/dist/index.mjs
    [14:06:29.662] ./node_modules/@tidbcloud/prisma-adapter/dist/index.mjs
    [14:06:29.662] ./auth.ts
    [14:06:29.662] 
    [14:06:29.662] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.662] A Node.js API is used (process.stderr at line: 150) which is not supported in the Edge Runtime.
    [14:06:29.662] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    [14:06:29.663] 
    [14:06:29.663] Import trace for requested module:
    [14:06:29.663] ./node_modules/@prisma/driver-adapter-utils/node_modules/@prisma/debug/dist/index.js
    [14:06:29.663] ./node_modules/@prisma/driver-adapter-utils/dist/index.mjs
    [14:06:29.663] ./node_modules/@tidbcloud/prisma-adapter/dist/index.mjs
    [14:06:29.663] ./auth.ts
    [14:06:29.666] 
    [14:06:45.565]  ✓ Compiled successfully
    [14:06:45.566]    Linting and checking validity of types ...
    [14:06:57.955]    Collecting page data ...
    [14:06:58.510] TypeError: Invalid URL
    [14:06:58.511]     at new URL (node:internal/url:797:36)
    [14:06:58.511]     at new e (/vercel/path0/.next/server/chunks/958.js:1:9916)
    [14:06:58.511]     at f (/vercel/path0/.next/server/chunks/958.js:1:11334)
    [14:06:58.512]     at 50731 (/vercel/path0/.next/server/app/api/feedback/[id]/route.js:1:2821)
    [14:06:58.512]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    [14:06:58.512]     at 64895 (/vercel/path0/.next/server/app/api/feedback/[id]/route.js:1:1502)
    [14:06:58.512]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    [14:06:58.512]     at t (/vercel/path0/.next/server/app/api/feedback/[id]/route.js:1:3575)
    [14:06:58.513]     at /vercel/path0/.next/server/app/api/feedback/[id]/route.js:1:3618
    [14:06:58.513]     at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1350) {
    [14:06:58.513]   code: 'ERR_INVALID_URL',
    [14:06:58.513]   input: 'gateway01.us-east-1.prod.aws.tidbcloud.com'
    [14:06:58.513] }
    [14:06:58.514] 
    [14:06:58.514] > Build error occurred
    [14:06:58.515] Error: Failed to collect page data for /api/feedback/[id]
    [14:06:58.515]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
    [14:06:58.516]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    [14:06:58.516]   type: 'Error'
    [14:06:58.516] }
    [14:06:58.553] Error: Command "npm run build" exited with 1
    [14:06:58.958]
